# Generated by Django 4.1.5 on 2023-01-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_enrollment_duedate_enrollment_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='dob',
            field=models.CharField(max_length=50),
        ),
    ]
