# Generated by Django 4.1.5 on 2023-01-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_enrollment_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
