# Generated by Django 4.1.5 on 2023-01-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectdate', models.DateTimeField(auto_now_add=True)),
                ('phonenumber', models.CharField(max_length=15)),
                ('login', models.CharField(max_length=200)),
                ('logout', models.CharField(max_length=200)),
                ('selectWorkout', models.CharField(max_length=200)),
                ('trainedBy', models.CharField(max_length=200)),
            ],
        ),
    ]
